# Generated by Django 5.2.1 on 2025-06-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_desc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_tech',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
