# Generated by Django 5.2.1 on 2025-06-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projects_project_desc_projects_project_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_slug',
            field=models.SlugField(blank=True),
        ),
    ]
