# Generated by Django 5.2.1 on 2025-06-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projects_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/'),
        ),
    ]
