# Generated by Django 5.2.1 on 2025-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projects_project_feature_projects_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
