# Generated by Django 5.2.1 on 2025-06-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_projects_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_desc',
            field=models.TextField(blank=True),
        ),
    ]
