# Generated by Django 5.2.1 on 2025-06-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_projects_project_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_long_text',
            field=models.TextField(blank=True),
        ),
    ]
