# Generated by Django 5.2.1 on 2025-06-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_projects_project_long_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
