# Generated by Django 5.2.1 on 2025-06-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_projects_project_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_screenshot1',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_screenshot2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/'),
        ),
    ]
